# Generated by Django 4.2.21 on 2025-05-22 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=100)),
                ('join_method', models.CharField(max_length=50)),
                ('maturity_interest_rate', models.FloatField()),
                ('preferential_condition', models.TextField()),
                ('join_limit', models.CharField(max_length=100)),
                ('join_target', models.CharField(max_length=100)),
                ('max_limit', models.CharField(max_length=100)),
                ('notice', models.TextField()),
                ('option_interest_type', models.CharField(max_length=50)),
                ('option_payment_type', models.CharField(max_length=50)),
                ('option_saving_period', models.CharField(max_length=50)),
                ('option_base_rate', models.FloatField()),
                ('option_max_rate', models.FloatField()),
                ('max_monthly_payment', models.IntegerField()),
                ('goal_asset', models.IntegerField()),
                ('target_date', models.DateField()),
                ('preferred_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='products.financialproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
    ]
