# Generated by Django 4.2.21 on 2025-05-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='join_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='join_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='join_target',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='max_limit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='notice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='option_interest_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='option_payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='option_saving_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='preferential_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
