# Generated by Django 4.2.21 on 2025-05-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_financialproduct_join_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='maturity_interest_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='option_base_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='option_max_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
