# Generated by Django 4.2.21 on 2025-05-23 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=20)),
                ('special_supply_units', models.IntegerField(blank=True, null=True)),
                ('special_applications', models.IntegerField(blank=True, null=True)),
                ('special_competition_rate', models.FloatField(blank=True, null=True)),
                ('general_supply_units', models.IntegerField(blank=True, null=True)),
                ('general_applications', models.IntegerField(blank=True, null=True)),
                ('general_competition_rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('notice_type', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('post_date', models.DateField()),
                ('deadline', models.DateField()),
                ('link_url', models.URLField()),
                ('supply_info', models.TextField()),
                ('schedule_info', models.TextField()),
                ('location_lat', models.FloatField()),
                ('location_lng', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeless_years', models.PositiveIntegerField()),
                ('num_dependents', models.PositiveIntegerField()),
                ('subscription_years', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='houses.subscriptionnotice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notice')},
            },
        ),
    ]
