# Generated by Django 4.2.21 on 2025-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecruitNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
                ("apply_start", models.DateField()),
                ("apply_end", models.DateField()),
                ("detail_url", models.URLField(unique=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200, null=True)),
                ("scale", models.CharField(blank=True, max_length=50, null=True)),
                ("notice_url", models.URLField(blank=True, null=True)),
            ],
        ),
    ]
