# Generated by Django 4.2.21 on 2025-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0002_recruitnotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="recruitnotice",
            name="winner_announcement_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
