# Generated by Django 4.2.21 on 2025-05-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_recruitnotice_winner_announcement_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recruitnotice",
            name="winner_announcement_date",
        ),
    ]
