# Generated by Django 4.2.21 on 2025-05-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0004_remove_recruitnotice_winner_announcement_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritenotice",
            name="notice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorited_by",
                to="houses.recruitnotice",
            ),
        ),
        migrations.DeleteModel(
            name="SubscriptionNotice",
        ),
    ]
