# Generated by Django 4.2.21 on 2025-05-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_favoritenotice_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitnotice',
            name='winner_announcement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
