# Generated by Django 4.2.21 on 2025-05-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_recruitnotice_winner_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitnotice',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
