# Generated by Django 4.2.21 on 2025-05-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_communitypost_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='category',
            field=models.CharField(choices=[('아파트', '아파트'), ('임의공급', '임의공급'), ('주택', '주택'), ('토지', '토지'), ('상가', '상가'), ('예적금', '예적금'), ('자유게시판', '자유게시판')], default='자유게시판', max_length=20),
        ),
    ]
